#!/bin/sh

version="$1"

if [ -z "$version" ]
then
    echo "Usage: $0 <revision>"
    exit 1
fi

if [ ! -e /boot/$version -a -e /usr/lib/linux-image-$version ]
then
    ln -s /usr/lib/linux-image-$version /boot/$version
fi

rm -f /boot/dtb /boot/initrd.img /boot/Image.gz
ln -s $version /boot/dtb
ln -s initrd.img-$version /boot/initrd.img
ln -s Image.gz-$version /boot/Image.gz
