#!/bin/sh

version="$1"

if [ -z "$version" ]
then
    echo "Usage: $0 <revision>"
    exit 1
fi

# TEMPORARY FIX: update u-boot on each kernel install
# This is needed for people with old images, will be removed in a few weeks
/usr/sbin/u-boot-install-pinephone

if echo $version | grep -qv pinephone
then
    echo "$version doesn't look like a PinePhone kernel, quitting..."
    exit 0
fi

if [ ! -e /boot/$version -a -e /usr/lib/linux-image-$version ]
then
    ln -s /usr/lib/linux-image-$version /boot/$version
fi

rm -f /boot/dtb /boot/initrd.img /boot/Image.gz
ln -s $version /boot/dtb
ln -s initrd.img-$version /boot/initrd.img
ln -s Image.gz-$version /boot/Image.gz
