#!/bin/sh

version="$1"

echo "Creating u-boot initrd..."
mkimage -T ramdisk -A arm64 -C none -n pinephone -d /boot/initrd.img-${version} /boot/initrd.uImg || return 1
echo "Creating boot script..."
mkimage -T script -A arm64 -C none -n pinephone -d /boot/boot.cmd /boot/boot.scr || return 1
