#!/bin/sh

version="$1"

if [ -z "$version" ]
then
    echo "Usage: $0 <revision>"
    exit 1
fi

echo "Creating boot script..."
sed -e "s/@@REVISION@@/$version/g" /usr/share/pinephone/boot.cmd.template > /boot/boot.cmd
mkimage -T script -A arm64 -C none -n pinephone -d /boot/boot.cmd /boot/boot.scr
